import "@/css/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>
        <header>헤더</header>
        {children}
        <footer>footer</footer>
      </body>
    </html>
  );
}
