import "@/css/globals.css";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import Header from "@/components/header";
config.autoAddCss = false;

export const metadata = {
  title: "PMG",
  description: "PMG Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>
        <div className="wrap">
          <Header/>
          <div className="in">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
